# Unique ID for your project in SonarQube
sonar.projectKey=devsecops-poc

# The display name in the SonarQube dashboard
sonar.projectName=DevSecOps POC

# Where the scanner should look for code
sonar.sources=.

# Folders to ignore (we don't want to scan third-party node_modules)
sonar.exclusions=node_modules/**, .github/**